### ISSUE TITLE
Not recognising normalise_input

### ISSUE THREAD

**Issue by st33l-butterfly** [st33l-butterfly/CM1101#1]
http://prntscr.com/8quh1x

**Comment by st33l-butterfly** [comment]
Create ending

**Comment by st33l-butterfly** [comment]
Finish print_menu

**Comment by NMelly** [comment]
The file name parser needs to be changed as it has a conflict with something else. Change it to parser1 or something and in the game.py file, import parser1 at the top

**Comment by st33l-butterfly** [comment]
change and upload?
